version: "3"
services:
  web:
    image: kalibek/scoreboard-web
    ports:
      - "80:80"
  api:
    image: kalibek/scoreboard-api
    ports:
      - "8000:8000"
    environment:
      - DB_FILE=/opt/scoreboard/data/game.db
    volumes:
      - ./data:/opt/scoreboard/data
